"""initial migration

Revision ID: 1a5d2f00d737
Revises: None
Create Date: 2016-12-19 18:06:36.237000

"""

# revision identifiers, used by Alembic.
revision = '1a5d2f00d737'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
