"""innital migration

Revision ID: 327c7967f3a0
Revises: None
Create Date: 2016-12-23 15:34:43.359000

"""

# revision identifiers, used by Alembic.
revision = '327c7967f3a0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
